// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanAI.Data;

#nullable disable

namespace PlanAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311105842_AddAppUser")]
    partial class AddAppUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PlanAI.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlanAI.Models.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectPlanId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPlanId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("PlanAI.Models.ProjectPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentLog")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("CriticalPathTaskIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCostMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCostMin")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("TeamMembers")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDurationDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProjectPlans");
                });

            modelBuilder.Entity("PlanAI.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BufferDays")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Dependencies")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnCriticalPath")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PhaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PlanAI.Models.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("MitigationNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<int>("Probability")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectPlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPlanId");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("PlanAI.Models.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxDailyHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("PlanAI.Models.Phase", b =>
                {
                    b.HasOne("PlanAI.Models.ProjectPlan", null)
                        .WithMany("Phases")
                        .HasForeignKey("ProjectPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlanAI.Models.ProjectPlan", b =>
                {
                    b.OwnsOne("PlanAI.Models.ResourceSummary", "ResourceSummary", b1 =>
                        {
                            b1.Property<Guid>("ProjectPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("CostMax")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("CostMin")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Equipment")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Headcount")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ProjectPlanId");

                            b1.ToTable("ProjectPlans");

                            b1.WithOwner()
                                .HasForeignKey("ProjectPlanId");
                        });

                    b.Navigation("ResourceSummary");
                });

            modelBuilder.Entity("PlanAI.Models.ProjectTask", b =>
                {
                    b.HasOne("PlanAI.Models.Phase", null)
                        .WithMany("Tasks")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlanAI.Models.Risk", b =>
                {
                    b.HasOne("PlanAI.Models.ProjectPlan", null)
                        .WithMany("Risks")
                        .HasForeignKey("ProjectPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlanAI.Models.Phase", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PlanAI.Models.ProjectPlan", b =>
                {
                    b.Navigation("Phases");

                    b.Navigation("Risks");
                });
#pragma warning restore 612, 618
        }
    }
}
